### ISSUE TITLE
mid channels argument in Reslayer

### ISSUE THREAD

**Issue by bach-zouk** [BlankCheng/FMNet.pytorch-DeepFunctionalMap#1]
missing 1 required positional argument: 'mid_channels'.

Hi, It seems you define the class with in_channels, mid_channels and out_channels but do not initiialize it with mid_channels.

**Comment by BlankCheng** [comment]
You're right. Thank you for pointing it out.
I've fixed it with default mid_channels=out_channels.
Best
Cheng
