### ISSUE TITLE
About final evaluation performance

### ISSUE THREAD

**Issue by lx709** [BlankCheng/FMNet.pytorch-DeepFunctionalMap#2]
Thanks for sharing your code! I'm wondering have you tested the performance as indicated in the original paper?

**Comment by BlankCheng** [comment]
Sorry for the late reply.
I have not tested yet since I'm not working on 3d vision anymore.
I think you can test it by setting "--phase test" using test.py, and modify your path to test data in dataloader.py correspondingly. Test data can also be generated by preprocess.py.
